<h1>{{titulo}}</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>Total</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        {{#transacciones}}
            <tr>
                <td>{{transaccionId}}</td>
                <td>{{fecha}}</td>
                <td>{{total}}</td>
                <td>{{usercod}}</td>
            </tr>
        {{/transacciones}}
    </tbody>
</table>